name: Concurrency 1

on:
  push:
    branches:
      - status-check  # Replace 'main' with your desired branch name

concurrency: concurrency-1

jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
