name: Concurrency 1
run-name: Concurrency 1 (${{ inputs.environment }})
on: [push]
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true

concurrency: concurrency-1
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30