name: Matrix
on: [push]


jobs:
  node-matrix:
      continue-on-error: false    
      strategy:
        matrix:   
          os: [ubuntu-latest, windows-latest]    
          node-version: [14, 15, 16] 
          includes:
            - os: ubuntu-latest
              is-ubuntu: true
        fail-fast: false  
      runs-on: ${{matrix.os}} 
      steps:     
        - run: node -v     
        - uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        - run: node -v
